# jaeger-all-in-one.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.48
          ports:
            - containerPort: 16686  # UI
            - containerPort: 14250  # gRPC collector
            - containerPort: 14268  # HTTP collector
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: observability
spec:
  ports:
    - port: 16686
      name: ui
    - port: 14250
      name: grpc-collector
    - port: 14268
      name: http-collector
  selector:
    app: jaeger
  type: ClusterIP

