apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.52
          ports:
            - containerPort: 16686 # UI
            - containerPort: 6831  # UDP
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: otel-demo
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: udp
      port: 6831
      targetPort: 6831
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-user/backend-app
          ports:
            - containerPort: 5000
          env:
            - name: OTEL_SERVICE_NAME
              value: "backend"
            - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
              value: "jaeger"
            - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
              value: "6831"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: otel-demo
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-user/frontend-app
          ports:
            - containerPort: 5000
          env:
            - name: OTEL_SERVICE_NAME
              value: "frontend"
            - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
              value: "jaeger"
            - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
              value: "6831"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: otel-demo
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000

